### ISSUE TITLE
Using Marshmallow Version 3 causes AttributeError when you follow the docs

### ISSUE THREAD

**Issue by datadidit** [marshmallow-code/apispec#200]
I believe the code causing the issue is below and this should be a simple fix

```
    if MARSHMALLOW_VERSION_INFO[0] < 3:
        # use getattr in case we're running against older versions of marshmallow.
        dump_to = getattr(field, 'dump_to', None)
        load_from = getattr(field, 'load_from', None)
        return dump_to or load_from or name
    else:
        return field.data_key or name
```

Example Test
```
from apispec import APISpec
from marshmallow import Schema, fields

SPEC = APISpec(
        title="Foo Bar",
        version="1.0.0",
        plugins = [
            'apispec.ext.marshmallow',
            'apispec.ext.flask'
        ]
    )

class GistSchema(Schema):
    id = fields.Int(data_key="id")
    content = fields.Str(data_key="content")

def test_definition():
    SPEC.definition('Gist', schema=GistSchema)
    print SPEC.to_yaml()


test_definition()
```

Stacktrace:

```
Traceback (most recent call last):
  File "/Users/mkwyche/workspace/api/tests/test_apispec.py", line 22, in <module>
    test_definition()
  File "/Users/mkwyche/workspace/api/tests/test_apispec.py", line 18, in test_definition
    SPEC.definition('Gist', schema=GistSchema)
  File "/Users/mkwyche/workspace/python/.env/lib/python2.7/site-packages/apispec/core.py", line 281, in definition
    ret.update(func(self, name, definition=ret, **kwargs))
  File "/Users/mkwyche/workspace/python/.env/lib/python2.7/site-packages/apispec/ext/marshmallow/__init__.py", line 109, in schema_definition_helper
    json_schema = swagger.schema2jsonschema(schema_instance, spec=spec, name=name)
  File "/Users/mkwyche/workspace/python/.env/lib/python2.7/site-packages/apispec/ext/marshmallow/swagger.py", line 545, in schema2jsonschema
    return fields2jsonschema(fields, schema, spec=spec, use_refs=use_refs, dump=dump, name=name)
  File "/Users/mkwyche/workspace/python/.env/lib/python2.7/site-packages/apispec/ext/marshmallow/swagger.py", line 609, in fields2jsonschema
    observed_field_name = _observed_name(field_obj, field_name)
  File "/Users/mkwyche/workspace/python/.env/lib/python2.7/site-packages/apispec/ext/marshmallow/swagger.py", line 102, in _observed_name
    return field.data_key or name
AttributeError: 'String' object has no attribute 'data_key'
```

**Comment by datadidit** [comment]
Note I've also been unable to get this to work when adding a data_key

**Comment by datadidit** [comment]
For anyone else who runs into this issue it's fixed by upgrading to 3.0.0b8 I was on 3.0.0b6 when I got the error.

**Comment by datadidit** [comment]
Made fix https://github.com/datadidit/apispec/commit/7741ab9e9d70d2308eaadb59462630c9204a9388 

Having issues with 2 tests that i need to investigate all other tests work fine.

**Comment by lafrech** [comment]
We don't mean to support old beta versions. As long as marshmallow 3 goes through the beta cycles, we try to keep apispec and other libs up to date. When a new beta version is out, users are supposed to move to the new beta.

Ultimately, apispec should support latest marshmallow 2 and latest marshmallow 3. Until support for marshmallow 2 is removed (not planned yet).

Thank you for using marshmallow 3 beta versions and reporting issues. This is how issues can be detected. If you don't want to face such inconvenience, you may stick to marshmallow 2 until marshmallow 3 is stabilized.

**Comment by datadidit** [comment]
@lafrech Thanks for the feedback. Learned a bunch looking through yalls code so time not all the way wasted lol
