### ISSUE TITLE
InvalidParameterError exception

### ISSUE THREAD

**Issue by dpgaspar** [marshmallow-code/apispec#473]
Hi,

On apispec>2.0.0 I'm getting:
```
apispec.exceptions.InvalidParameterError: Missing keys ['name', 'in'] for parameter
```

I may be mistaken but it seems that I do have `name` and `in` on all parameters
Once more I'm sorry for the long JSON spec:

```
{
  "components": {
    "parameters": {
      "get_info_schema": {
        "in": "query",
        "name": "q",
        "schema": {
          "properties": {
            "add_columns": {
              "additionalProperties": {
                "properties": {
                  "page": {
                    "type": "integer"
                  },
                  "page_size": {
                    "type": "integer"
                  }
                },
                "type": "object"
              },
              "type": "object"
            },
            "keys": {
              "items": {
                "enum": [
                  "add_columns",
                  "edit_columns",
                  "filters",
                  "permissions",
                  "add_title",
                  "edit_title",
                  "none"
                ],
                "type": "string"
              },
              "type": "array"
            }
          },
          "type": "object"
        }
      },
      "get_item_schema": {
        "in": "query",
        "name": "q",
        "schema": {
          "properties": {
            "columns": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "keys": {
              "items": {
                "enum": [
                  "show_columns",
                  "description_columns",
                  "label_columns",
                  "show_title",
                  "none"
                ],
                "type": "string"
              },
              "type": "array"
            }
          },
          "type": "object"
        }
      },
      "get_list_schema": {
        "in": "query",
        "name": "q",
        "schema": {
          "properties": {
            "columns": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "filters": {
              "items": {
                "properties": {
                  "col": {
                    "type": "string"
                  },
                  "opr": {
                    "type": "string"
                  },
                  "value": {
                    "anyOf": [
                      {
                        "type": "number"
                      },
                      {
                        "type": "string"
                      },
                      {
                        "type": "boolean"
                      }
                    ]
                  }
                },
                "type": "object"
              },
              "type": "array"
            },
            "keys": {
              "items": {
                "enum": [
                  "list_columns",
                  "order_columns",
                  "label_columns",
                  "description_columns",
                  "list_title",
                  "none"
                ],
                "type": "string"
              },
              "type": "array"
            },
            "order_column": {
              "type": "string"
            },
            "order_direction": {
              "enum": [
                "asc",
                "desc"
              ],
              "type": "string"
            },
            "page": {
              "type": "integer"
            },
            "page_size": {
              "type": "integer"
            }
          },
          "type": "object"
        }
      }
    },
    "responses": {
      "400": {
        "content": {
          "application/json": {
            "schema": {
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "type": "object"
            }
          }
        },
        "description": "Bad request"
      },
      "401": {
        "content": {
          "application/json": {
            "schema": {
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "type": "object"
            }
          }
        },
        "description": "Unauthorized"
      },
      "404": {
        "content": {
          "application/json": {
            "schema": {
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "type": "object"
            }
          }
        },
        "description": "Not found"
      },
      "422": {
        "content": {
          "application/json": {
            "schema": {
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "type": "object"
            }
          }
        },
        "description": "Could not process entity"
      },
      "500": {
        "content": {
          "application/json": {
            "schema": {
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "type": "object"
            }
          }
        },
        "description": "Fatal error"
      }
    },
    "schemas": {
      "GroupModelApi.get": {
        "properties": {
          "name": {
            "maxLength": 50,
            "type": "string"
          }
        },
        "required": [
          "name"
        ],
        "type": "object"
      },
      "GroupModelApi.get_list": {
        "properties": {
          "name": {
            "maxLength": 50,
            "type": "string"
          }
        },
        "required": [
          "name"
        ],
        "type": "object"
      },
      "GroupModelApi.post": {
        "properties": {
          "name": {
            "maxLength": 50,
            "type": "string"
          }
        },
        "required": [
          "name"
        ],
        "type": "object"
      },
      "GroupModelApi.put": {
        "properties": {
          "name": {
            "maxLength": 50,
            "type": "string"
          }
        },
        "required": [
          "name"
        ],
        "type": "object"
      },
      "get_info_schema": {
        "properties": {
          "add_columns": {
            "additionalProperties": {
              "properties": {
                "page": {
                  "type": "integer"
                },
                "page_size": {
                  "type": "integer"
                }
              },
              "type": "object"
            },
            "type": "object"
          },
          "keys": {
            "items": {
              "enum": [
                "add_columns",
                "edit_columns",
                "filters",
                "permissions",
                "add_title",
                "edit_title",
                "none"
              ],
              "type": "string"
            },
            "type": "array"
          }
        },
        "type": "object"
      },
      "get_item_schema": {
        "properties": {
          "columns": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "keys": {
            "items": {
              "enum": [
                "show_columns",
                "description_columns",
                "label_columns",
                "show_title",
                "none"
              ],
              "type": "string"
            },
            "type": "array"
          }
        },
        "type": "object"
      },
      "get_list_schema": {
        "properties": {
          "columns": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "filters": {
            "items": {
              "properties": {
                "col": {
                  "type": "string"
                },
                "opr": {
                  "type": "string"
                },
                "value": {
                  "anyOf": [
                    {
                      "type": "number"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "boolean"
                    }
                  ]
                }
              },
              "type": "object"
            },
            "type": "array"
          },
          "keys": {
            "items": {
              "enum": [
                "list_columns",
                "order_columns",
                "label_columns",
                "description_columns",
                "list_title",
                "none"
              ],
              "type": "string"
            },
            "type": "array"
          },
          "order_column": {
            "type": "string"
          },
          "order_direction": {
            "enum": [
              "asc",
              "desc"
            ],
            "type": "string"
          },
          "page": {
            "type": "integer"
          },
          "page_size": {
            "type": "integer"
          }
        },
        "type": "object"
      }
    },
    "securitySchemes": {
      "jwt": {
        "bearerFormat": "JWT",
        "scheme": "bearer",
        "type": "http"
      },
      "jwt_refresh": {
        "bearerFormat": "JWT",
        "scheme": "bearer",
        "type": "http"
      }
    }
  },
  "info": {
    "description": "F.A.B. Example",
    "title": "F.A.B. Example",
    "version": "v1"
  },
  "openapi": "3.0.2",
  "paths": {
    "/group/": {
      "get": {
        "parameters": [
          {
            "in": "query",
            "name": "q",
            "schema": {
              "properties": {
                "columns": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                },
                "filters": {
                  "items": {
                    "properties": {
                      "col": {
                        "type": "string"
                      },
                      "opr": {
                        "type": "string"
                      },
                      "value": {
                        "anyOf": [
                          {
                            "type": "number"
                          },
                          {
                            "type": "string"
                          },
                          {
                            "type": "boolean"
                          }
                        ]
                      }
                    },
                    "type": "object"
                  },
                  "type": "array"
                },
                "keys": {
                  "items": {
                    "enum": [
                      "list_columns",
                      "order_columns",
                      "label_columns",
                      "description_columns",
                      "list_title",
                      "none"
                    ],
                    "type": "string"
                  },
                  "type": "array"
                },
                "order_column": {
                  "type": "string"
                },
                "order_direction": {
                  "enum": [
                    "asc",
                    "desc"
                  ],
                  "type": "string"
                },
                "page": {
                  "type": "integer"
                },
                "page_size": {
                  "type": "integer"
                }
              },
              "type": "object"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "description_columns": {
                      "type": "object"
                    },
                    "ids": {
                      "items": {
                        "type": "string"
                      },
                      "type": "array"
                    },
                    "label_columns": {
                      "type": "object"
                    },
                    "list_columns": {
                      "items": {
                        "type": "string"
                      },
                      "type": "array"
                    },
                    "list_title": {
                      "type": "string"
                    },
                    "order_columns": {
                      "items": {
                        "type": "string"
                      },
                      "type": "array"
                    },
                    "result": {
                      "items": {
                        "properties": {
                          "name": {
                            "maxLength": 50,
                            "type": "string"
                          }
                        },
                        "required": [
                          "name"
                        ],
                        "type": "object"
                      },
                      "type": "array"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Items from Model"
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Bad request"
          },
          "401": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Unauthorized"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Could not process entity"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Fatal error"
          }
        },
        "security": [
          {
            "jwt": []
          }
        ],
        "tags": [
          "GroupModelApi"
        ]
      },
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "name": {
                    "maxLength": 50,
                    "type": "string"
                  }
                },
                "required": [
                  "name"
                ],
                "type": "object"
              }
            }
          },
          "description": "Model schema",
          "required": true
        },
        "responses": {
          "201": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "result": {
                      "properties": {
                        "name": {
                          "maxLength": 50,
                          "type": "string"
                        }
                      },
                      "required": [
                        "name"
                      ],
                      "type": "object"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Item inserted"
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Bad request"
          },
          "401": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Unauthorized"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Could not process entity"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Fatal error"
          }
        },
        "security": [
          {
            "jwt": []
          }
        ],
        "tags": [
          "GroupModelApi"
        ]
      }
    },
    "/group/_info": {
      "get": {
        "parameters": [
          {
            "in": "query",
            "name": "q",
            "schema": {
              "properties": {
                "add_columns": {
                  "additionalProperties": {
                    "properties": {
                      "page": {
                        "type": "integer"
                      },
                      "page_size": {
                        "type": "integer"
                      }
                    },
                    "type": "object"
                  },
                  "type": "object"
                },
                "keys": {
                  "items": {
                    "enum": [
                      "add_columns",
                      "edit_columns",
                      "filters",
                      "permissions",
                      "add_title",
                      "edit_title",
                      "none"
                    ],
                    "type": "string"
                  },
                  "type": "array"
                }
              },
              "type": "object"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "add_columns": {
                      "type": "object"
                    },
                    "edit_columns": {
                      "type": "object"
                    },
                    "filters": {
                      "type": "object"
                    },
                    "permissions": {
                      "items": {
                        "type": "string"
                      },
                      "type": "array"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Item from Model"
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Bad request"
          },
          "401": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Unauthorized"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Could not process entity"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Fatal error"
          }
        },
        "security": [
          {
            "jwt": []
          }
        ],
        "tags": [
          "GroupModelApi"
        ]
      }
    },
    "/group/{pk}": {
      "delete": {
        "parameters": [
          {
            "in": "path",
            "name": "pk",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Item deleted"
          },
          "404": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Not found"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Could not process entity"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Fatal error"
          }
        },
        "security": [
          {
            "jwt": []
          }
        ],
        "tags": [
          "GroupModelApi"
        ]
      },
      "get": {
        "parameters": [
          {
            "in": "path",
            "name": "pk",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "in": "query",
            "name": "q",
            "schema": {
              "properties": {
                "columns": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                },
                "keys": {
                  "items": {
                    "enum": [
                      "show_columns",
                      "description_columns",
                      "label_columns",
                      "show_title",
                      "none"
                    ],
                    "type": "string"
                  },
                  "type": "array"
                }
              },
              "type": "object"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "description_columns": {
                      "type": "object"
                    },
                    "id": {
                      "type": "string"
                    },
                    "label_columns": {
                      "type": "object"
                    },
                    "result": {
                      "properties": {
                        "name": {
                          "maxLength": 50,
                          "type": "string"
                        }
                      },
                      "required": [
                        "name"
                      ],
                      "type": "object"
                    },
                    "show_columns": {
                      "items": {
                        "type": "string"
                      },
                      "type": "array"
                    },
                    "show_title": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Item from Model"
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Bad request"
          },
          "401": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Unauthorized"
          },
          "404": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Not found"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Could not process entity"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Fatal error"
          }
        },
        "security": [
          {
            "jwt": []
          }
        ],
        "tags": [
          "GroupModelApi"
        ]
      },
      "put": {
        "parameters": [
          {
            "in": "path",
            "name": "pk",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "name": {
                    "maxLength": 50,
                    "type": "string"
                  }
                },
                "required": [
                  "name"
                ],
                "type": "object"
              }
            }
          },
          "description": "Model schema",
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "result": {
                      "properties": {
                        "name": {
                          "maxLength": 50,
                          "type": "string"
                        }
                      },
                      "required": [
                        "name"
                      ],
                      "type": "object"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Item changed"
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Bad request"
          },
          "401": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Unauthorized"
          },
          "404": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Not found"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Could not process entity"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Fatal error"
          }
        },
        "security": [
          {
            "jwt": []
          }
        ],
        "tags": [
          "GroupModelApi"
        ]
      }
    },
    "/openapi/{version}/_openapi": {
      "get": {
        "parameters": [
          {
            "in": "path",
            "name": "version",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            },
            "description": "Item from Model"
          },
          "404": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Not found"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Fatal error"
          }
        },
        "security": [
          {
            "jwt": []
          }
        ],
        "tags": [
          "OpenApi"
        ]
      }
    },
    "/security/login": {
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "password": {
                    "type": "string"
                  },
                  "provider": {
                    "enum": [
                      "db",
                      "ldap"
                    ],
                    "type": "string"
                  },
                  "refresh": {
                    "type": "boolean"
                  },
                  "username": {
                    "type": "string"
                  }
                },
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "access_token": {
                      "type": "string"
                    },
                    "refresh_token": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Authentication Successful"
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Bad request"
          },
          "401": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Unauthorized"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Fatal error"
          }
        },
        "tags": [
          "SecurityApi"
        ]
      }
    },
    "/security/refresh": {
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "refresh_token": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Refresh Successful"
          },
          "401": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Unauthorized"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Fatal error"
          }
        },
        "security": [
          {
            "jwt_refresh": []
          }
        ],
        "tags": [
          "SecurityApi"
        ]
      }
    }
  },
  "servers": [
    {
      "url": "/api/v1"
    }
  ]
}
```

**Comment by dpgaspar** [comment]
Hi, 

Any news on this, can you help?

**Comment by lafrech** [comment]
Hi.

I thought I had answered already. Maybe I didn't submit my comment.

It's hard to help without a stack trace and a piece of code to reproduce.

How do you generate that spec? With the same code and apispec < 2?

**Comment by dpgaspar** [comment]
Yes that spec is generated with the same code and apispec < 2

My question is: all my parameters contain "name" and "in" right? This is what the `InvalidParameterError` is checking, am I missing something?

**Comment by dpgaspar** [comment]
Sorry to insist, can you help, I really would like to avoid setting flask-appbuilder dependency for apispec < 2

**Comment by lafrech** [comment]
I'm sorry. Without a reproducible code I can't really do anything useful.

A stracktrace would be a minimum. At least it could lead you to where the problem lies.

**Comment by dpgaspar** [comment]
Sure, stacktrace when accessing the endpoint that generated the spec:

```
019-07-18 11:38:38,937:ERROR:root:Missing keys ['name', 'in'] for parameter
Traceback (most recent call last):
  File "/opt/vol1/home/dpgaspar/workarea/v_fab/lib/python3.6/site-packages/flask_appbuilder/api/__init__.py", line 79, in wraps
    return f(self, *args, **kwargs)
  File "/opt/vol1/home/dpgaspar/workarea/v_fab/lib/python3.6/site-packages/flask_appbuilder/api/manager.py", line 44, in get
    base_api.add_api_spec(api_spec)
  File "/opt/vol1/home/dpgaspar/workarea/v_fab/lib/python3.6/site-packages/flask_appbuilder/api/__init__.py", line 413, in add_api_spec
    api_spec.path(path=path, operations=operations)
  File "/opt/vol1/home/dpgaspar/workarea/v_fab/lib/python3.6/site-packages/apispec/core.py", line 363, in path
    clean_operations(operations, self.openapi_version.major)
  File "/opt/vol1/home/dpgaspar/workarea/v_fab/lib/python3.6/site-packages/apispec/core.py", line 102, in clean_operations
    operation["parameters"], openapi_major_version
  File "/opt/vol1/home/dpgaspar/workarea/v_fab/lib/python3.6/site-packages/apispec/core.py", line 57, in clean_parameters
    "Missing keys {} for parameter".format(missing_attrs)
apispec.exceptions.InvalidParameterError: Missing keys ['name', 'in'] for parameter
2019-07-18 11:38:38,938:INFO:werkzeug:127.0.0.1 - - [18/Jul/2019 11:38:38] "GET /api/v1/_openapi HTTP/1.1" 500 -
```

This is the method that add's the spec: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/api/__init__.py#L403

If you think this might be a bug on apispec, maybe I can try to make a PR, or am I missing something on my generated spec?

**Comment by lafrech** [comment]
Please add a print in `clean_operations` to see what's in the operation:

```py
for operation in (operations or {}).values():
    if "parameters" in operation:
        print(operation)
        [...]
        operation["parameters"] = clean_parameters(
            operation["parameters"], openapi_major_version
        )
```

**Comment by dpgaspar** [comment]
Sorry, did not understood your request, added a `print(operations)` exactly before the `api_spec.path`
output:

```
{'post': {'requestBody': {'required': True, 'content': {'application/json': {'schema': {'type': 'object', 'properties': {'username': {'type': 'string'}, 'password': {'type': 'string'}, 'provider': {'type': 'string', 'enum': ['db', 'ldap']}, 'refresh': {'type': 'boolean'}}}}}}, 'responses': {200: {'description': 'Authentication Successful', 'content': {'application/json': {'schema': {'type': 'object', 'properties': {'access_token': {'type': 'string'}, 'refresh_token': {'type': 'string'}}}}}}, 400: {'$ref': '#/components/responses/400'}, 401: {'$ref': '#/components/responses/401'}, 500: {'$ref': '#/components/responses/500'}}}}
{'post': {'responses': {200: {'description': 'Refresh Successful', 'content': {'application/json': {'schema': {'type': 'object', 'properties': {'refresh_token': {'type': 'string'}}}}}}, 401: {'$ref': '#/components/responses/401'}, 500: {'$ref': '#/components/responses/500'}}, 'security': [{'jwt_refresh': []}]}}
{'get': {'parameters': [{'in': 'path', 'schema': {'type': 'string'}, 'name': 'version'}], 'responses': {200: {'description': 'Item from Model', 'content': {'application/json': {'schema': {'type': 'object'}}}}, 404: {'$ref': '#/components/responses/404'}, 500: {'$ref': '#/components/responses/500'}}, 'security': [{'jwt': []}]}}
{'delete': {'parameters': [{'in': 'path', 'schema': {'type': 'integer'}, 'name': 'pk'}], 'responses': {200: {'description': 'Item deleted', 'content': {'application/json': {'schema': {'type': 'object', 'properties': {'message': {'type': 'string'}}}}}}, 404: {'$ref': '#/components/responses/404'}, 422: {'$ref': '#/components/responses/422'}, 500: {'$ref': '#/components/responses/500'}}, 'security': [{'jwt': []}]}}
{'get': {'parameters': [{'in': 'path', 'schema': {'type': 'integer'}, 'name': 'pk'}, {'$ref': '#/components/parameters/get_item_schema'}], 'responses': {200: {'description': 'Item from Model', 'content': {'application/json': {'schema': {'type': 'object', 'properties': {'label_columns': {'type': 'object'}, 'show_columns': {'type': 'array', 'items': {'type': 'string'}}, 'description_columns': {'type': 'object'}, 'show_title': {'type': 'string'}, 'id': {'type': 'string'}, 'result': {'$ref': '#/components/schemas/GroupModelApi.get'}}}}}}, 400: {'$ref': '#/components/responses/400'}, 401: {'$ref': '#/components/responses/401'}, 404: {'$ref': '#/components/responses/404'}, 422: {'$ref': '#/components/responses/422'}, 500: {'$ref': '#/components/responses/500'}}, 'security': [{'jwt': []}]}}
2019-07-18 13:43:07,289:ERROR:root:Missing keys ['name', 'in'] for parameter
Traceback (most recent call last):
  File "/opt/vol1/home/dpgaspar/workarea/v_fab/lib/python3.6/site-packages/Flask_AppBuilder-2.1.6-py3.6.egg/flask_appbuilder/api/__init__.py", line 79, in wraps
    return f(self, *args, **kwargs)
  File "/opt/vol1/home/dpgaspar/workarea/v_fab/lib/python3.6/site-packages/Flask_AppBuilder-2.1.6-py3.6.egg/flask_appbuilder/api/manager.py", line 44, in get
    base_api.add_api_spec(api_spec)
  File "/opt/vol1/home/dpgaspar/workarea/v_fab/lib/python3.6/site-packages/Flask_AppBuilder-2.1.6-py3.6.egg/flask_appbuilder/api/__init__.py", line 414, in add_api_spec
    api_spec.path(path=path, operations=operations)
  File "/opt/vol1/home/dpgaspar/workarea/v_fab/lib/python3.6/site-packages/apispec/core.py", line 363, in path
    clean_operations(operations, self.openapi_version.major)
  File "/opt/vol1/home/dpgaspar/workarea/v_fab/lib/python3.6/site-packages/apispec/core.py", line 102, in clean_operations
    operation["parameters"], openapi_major_version
  File "/opt/vol1/home/dpgaspar/workarea/v_fab/lib/python3.6/site-packages/apispec/core.py", line 57, in clean_parameters
    "Missing keys {} for parameter".format(missing_attrs)
apispec.exceptions.InvalidParameterError: Missing keys ['name', 'in'] for parameter
2019-07-18 13:43:07,290:INFO:werkzeug:127.0.0.1 - - [18/Jul/2019 13:43:07] "GET /api/v1/_openapi HTTP/1.1" 500 -
```
Seems like it's the `$ref` parameter:
```
 [
    {'in': 'path', 'schema': {'type': 'integer'}, 'name': 'pk'}, 
    {'$ref': '#/components/parameters/get_item_schema'}
]
```
That references:
```
"get_item_schema": {
        "in": "query",
        "name": "q",
        "schema": {
          "properties": {
            "columns": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "keys": {
              "items": {
                "enum": [
                  "show_columns",
                  "description_columns",
                  "label_columns",
                  "show_title",
                  "none"
                ],
                "type": "string"
              },
              "type": "array"
            }
          },
          "type": "object"
        }
      },

```

**Comment by lafrech** [comment]
This is documented in the upgrading section of the docs...

https://apispec.readthedocs.io/en/stable/upgrading.html#components-must-be-referenced-by-id-not-full-path

For a full history, see

- https://github.com/marshmallow-code/apispec/issues/463
- https://github.com/marshmallow-code/apispec/pull/465/files

**Comment by dpgaspar** [comment]
Oh, I see, thank you for your help.

**Comment by aalvrz** [comment]
@lafrech I read [_Components must be referenced by ID, not full path_](https://apispec.readthedocs.io/en/stable/upgrading.html#components-must-be-referenced-by-id-not-full-path) but I am still struggling to understand how to make this work...:

```yaml
parameters:
  - name: some_id
    description: Some ID
    in: path
    required: true
    schema:
      type: integer
      example: 14875
  - $ref: "q"  # I believe this is what the doc refers to referencing by ID?

  responses:
    "401":
      $ref: "#/components/responses/UnauthorizedError"  # Weird thing is I can reference these by path and they work fine
```

I have registered the parameter component as:

```python
api_spec.components.parameter(
    "q", "query", component={"name": "q", "description": "Apply search to query", "schema": {"type": "string"}}
)
```

But I still get the same error:

```
Traceback (most recent call last):
  File "build_api_docs.py", line 8, in <module>
    from app import app  # noqa
  File "/home/andres/gap/ssv-api/app.py", line 128, in <module>
    from chalicelib.routes.sites import site_routes  # noqa: E402
  File "/home/andres/gap/ssv-api/chalicelib/routes/sites.py", line 237, in <module>
    api_spec.path("/v2/teams/{team_id}/sites", resource=get_team_sites)
  File "/home/andres/gap/ssv-api/venv/lib/python3.8/site-packages/apispec/core.py", line 306, in path
    self.clean_operations(operations)
  File "/home/andres/gap/ssv-api/venv/lib/python3.8/site-packages/apispec/core.py", line 409, in clean_operations
    operation["parameters"] = self.clean_parameters(operation["parameters"])
  File "/home/andres/gap/ssv-api/venv/lib/python3.8/site-packages/apispec/core.py", line 365, in clean_parameters
    raise InvalidParameterError(
apispec.exceptions.InvalidParameterError: Missing keys ['name', 'in'] for parameter
```

---

I am using apispec==4.6.0

**Comment by memjr** [comment]
@aalvrz, @dpgaspar , have you been able to get any progress on this?  I'm having the same issue.  Using flask-appbuilder and while the api works, the swagger doc is an issue, and it seems all my boss cares about is the swagger working so we can direct our users to the swagger page for help on how to use the api.

I'm proficient enough in python to use it, but not enough to step through the the source code to see where the change needs to be made.

Any help would be greatly appreciated.

**Comment by lafrech** [comment]
@aalvrz don't pass `{"$ref": "q"}` but just `"q"`.
