### ISSUE TITLE
Example in Readme Fails in python 3.6.3

### ISSUE THREAD

**Issue by thenetimp** [marshmallow-code/apispec#503]
```
python spectest.py
Traceback (most recent call last):
  File "spectest.py", line 1, in <module>
    from apispec import APISpec
  File "/Users/jandrews/flaskbase/apispec.py", line 1, in <module>
    from apispec import APISpec
ImportError: cannot import name 'APISpec'
```

Python 3.6.3 in a virtual environment.  Unable to use the sample script in the Readme.md

**Comment by thenetimp** [comment]
I just put it in a clean venv and it is working there.   Not sure if it's failing because of another library installed, or if it just didn't install correctly I am continuing to investigate this may be nothing, I'll let you know what I find.

**Comment by thenetimp** [comment]
Best I can tell it was a bad install.  I moved my code into new project venv and apispec is working.  Very strange.
