### ISSUE TITLE
Marshmallow 1.2 is not supported

### ISSUE THREAD

**Issue by etataurov** [marshmallow-code/apispec#58]
Doc states that
`Requires marshmallow>=1.2.`
but
I've got an error with marshmallow==1.2.6

```
Traceback (most recent call last):
  File "api_spec.py", line 12, in <module>
    spec.definition('UserProfile', schema=ProfileSchema)
  File "/Users/etataurov/Envs/click_server_asyncio/lib/python3.5/site-packages/apispec/core.py", line 191, in definition
    ret.update(func(self, name, **kwargs))
  File "/Users/etataurov/Envs/click_server_asyncio/lib/python3.5/site-packages/apispec/ext/marshmallow/__init__.py", line 30, in schema_definition_helper
    return swagger.schema2jsonschema(schema, spec=spec)
  File "/Users/etataurov/Envs/click_server_asyncio/lib/python3.5/site-packages/apispec/ext/marshmallow/swagger.py", line 276, in schema2jsonschema
    return fields2jsonschema(fields, schema, spec=spec, use_refs=use_refs, dump=dump)
  File "/Users/etataurov/Envs/click_server_asyncio/lib/python3.5/site-packages/apispec/ext/marshmallow/swagger.py", line 333, in fields2jsonschema
    if field_name in exclude or (field_obj.dump_only and not dump):
AttributeError: 'String' object has no attribute 'dump_only'
```

because _dump_only_ was added in 2.0 https://marshmallow.readthedocs.org/en/latest/changelog.html

I guess it is probably OK to drop 1.2 support, but docs should be fixed then.
Thanks

**Comment by sloria** [comment]
Good catch. apispec supports marshmallow>=2.0.
