### ISSUE TITLE
[MarshmallowPlugin]: spec.components.schema raises AttributeError ('copy') 

### ISSUE THREAD

**Issue by PietroPasotti** [marshmallow-code/apispec#644]
When trying out the 'barebone' example on how to add a marshmallow schema as documented, I get an error.

```
from apispec import APISpec
from apispec.ext.marshmallow import MarshmallowPlugin
from apispec_webframeworks.flask import FlaskPlugin
from marshmallow import Schema, fields


spec = APISpec(
    title="Gisty",
    version="1.0.0",
    openapi_version="3.0.2",
    info=dict(description="A minimal gist API"),
    plugins=[FlaskPlugin(), MarshmallowPlugin()],
)


class GistParameter(Schema):
    gist_id = fields.Int()


class GistSchema(Schema):
    id = fields.Nested(GistParameter)
    content = fields.Str()


spec.components.schema("Gist", GistSchema)

print(spec.to_yaml())
```

output:

```
Traceback (most recent call last):
  File "XXX/marshmallow_to_swagger.py", line 30, in <module>
    spec.components.schema("Gist", GistSchema)
  File "XXX\lib\site-packages\apispec\core.py", line 80, in schema
    ret = component.copy()
AttributeError: type object 'GistSchema' has no attribute 'copy'

```

**Comment by PietroPasotti** [comment]
never mind, looks like I was missing the kwarg 'schema' in the spec.components.schema call, should have copied more carefully.
